INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:21:37] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:21:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:21:47] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:21:50] "GET /2 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:21:52] "GET /3 HTTP/1.1" 200 -
INFO:app:Status request successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:22:11] "GET /healthz HTTP/1.1" 200 -
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 114, in metrics
    response=json.dumps({"status": "success", "code": 0,
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:22:16] "GET /metrics HTTP/1.1" 500 -
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 114, in metrics
    response=json.dumps({"status": "success", "code": 0,
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:23:06] "GET /metrics HTTP/1.1" 500 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:23:20] "GET / HTTP/1.1" 200 -
INFO:app:Status request successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:23:23] "GET /healthz HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:23:31] "GET /about HTTP/1.1" 200 -
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 114, in metrics
    response=json.dumps({"status": "success", "code": 0,
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:23:34] "GET /metrics HTTP/1.1" 500 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 115, in metrics
    "data": {"db_connection_count": DbConnectionCount, "post_count": len(posts)}}),
TypeError: object of type 'int' has no len()
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:26:20] "GET /metrics HTTP/1.1" 500 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 117, in metrics
    "data": {"db_connection_count": DbConnectionCount, "post_count": posts)}}),
TypeError: object of type 'int' has no len()
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:28:11] "GET /metrics HTTP/1.1" 500 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:28:50] "GET /metrics HTTP/1.1" 200 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:29:41] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:29:44] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:29:45] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:29:47] "GET /2 HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:29:52] "GET /metrics HTTP/1.1" 200 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 116, in metrics
    "data": {"db_connection_count": DbConnectionCount, "post_count": posts}}),
NameError: name 'posts' is not defined
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:31:20] "GET /metrics HTTP/1.1" 500 -
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 50, in post
    post = get_post(post_id)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 27, in get_post
    postsCounts += 1
UnboundLocalError: local variable 'postsCounts' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:31:23] "GET /1 HTTP/1.1" 500 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:31:45] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:31:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:31:49] "GET /5 HTTP/1.1" 200 -
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Udacity\Nanodegree\project\techtrends\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Udacity\Nanodegree\project\techtrends\app.py", line 117, in metrics
    "data": {"db_connection_count": DbConnectionCount, "post_count": posts}}),
NameError: name 'posts' is not defined
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:31:54] "GET /metrics HTTP/1.1" 500 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:32:12] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:32:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:32:17] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:32:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:32:19] "GET /5 HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:32:23] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:53:48] "GET /STATUS HTTP/1.1" 404 -
INFO:app:Status request successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:53:54] "GET /healthz HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:54:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:54:48] "GET /1 HTTP/1.1" 200 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:58:04] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:58:04] "GET /1 HTTP/1.1" 200 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:00] "GET / HTTP/1.1" 200 -
INFO:app:About page successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:06] "GET /about HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:08] "GET / HTTP/1.1" 200 -
INFO:app:Article with id = "2020 CNCF Annual Report" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:08] "GET /1 HTTP/1.1" 200 -
INFO:app:About page successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:10] "GET /about HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:10] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:12] "GET / HTTP/1.1" 200 -
INFO:app:Article with id = "Kubernetes v1.20 Release Notes" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 21:59:13] "GET /3 HTTP/1.1" 200 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:08] "GET / HTTP/1.1" 200 -
INFO:app:Article "{0}" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:09] "GET /2 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:10] "GET / HTTP/1.1" 200 -
INFO:app:Article "{0}" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:10] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:11] "GET / HTTP/1.1" 200 -
INFO:app:Article "{0}" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:12] "GET /4 HTTP/1.1" 200 -
INFO:app:Inicio
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:35] "GET / HTTP/1.1" 200 -
INFO:app:Article "2020 CNCF Annual Report" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:36] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:37] "GET / HTTP/1.1" 200 -
INFO:app:Article "Kubernetes v1.20 Release Notes" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:37] "GET /3 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:38] "GET / HTTP/1.1" 200 -
INFO:app:Article "Kubernetes Certification" successfull
INFO:werkzeug:127.0.0.1 - - [11/Sep/2021 22:00:39] "GET /6 HTTP/1.1" 200 -
